name: Deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    env:
      SPREADSHEET_API_KEY: ${{ secrets.SPREADSHEET_API_KEY }}
      PRETALX_TOKEN: ${{secrets.PRETALX_TOKEN}}


    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v4
        with:
          version: 7.12.2

      - name: Setup node env ðŸ—
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install env dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies ðŸ‘¨ðŸ»â€ðŸ’»
        run: pnpm install --frozen-lockfile

      - name: Linting ðŸ”
        run: pnpm run lint

      - name: Download static resource
        run: pnpm run tool:download-static-resource

      - name: Build production ðŸš§
        run: pnpm run build
        
      - name: List public file
        run: du -hc ./public | sort -h

      - name: List dist file
        run: du -hc ./dist | sort -h

      - name: get all size
        run: du -shc ./
        
      - name: get system tmp size
        run: sudo du -shc /tmp 2> /dev/null

      - name: get system all size
        run: sudo du -shc / 2> /dev/null
        
      - name: Deploy ðŸ“¡
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
